export interface CollegeEntry {
  name: string;
  strength: string;
  notes: string;
}

export interface CountryCollegeData {
  name: string;
  slug: string;
  flag: string;
  top: CollegeEntry[];
  moderate: CollegeEntry[];
}

export const countryCollegeData: CountryCollegeData[] = [
  {
    name: "Canada",
    slug: "canada",
    flag: "🇨🇦",
    top: [
      { name: "University of Toronto", strength: "Medical / Engineering / Law", notes: "Canada's #1 ranked university; world-class Temerty Faculty of Medicine and Faculty of Law." },
      { name: "McGill University", strength: "Medical / Law / Management", notes: "Known as the 'Harvard of Canada'; strong medicine, law, and Desautels management programs." },
      { name: "University of British Columbia (UBC)", strength: "Engineering / Medical / Business", notes: "Top-ranked for forestry, engineering, and the Sauder School of Business." },
      { name: "University of Waterloo", strength: "Engineering / Computer Science", notes: "Global leader in engineering and CS; world's largest co-op education program." },
      { name: "McMaster University", strength: "Medical", notes: "Pioneered the problem-based learning (PBL) medical curriculum used worldwide." },
      { name: "Western University (incl. Ivey)", strength: "Management / Engineering", notes: "Ivey Business School is one of the top management schools in Canada." },
      { name: "Queen's University", strength: "Engineering / Management / Law", notes: "Smith School of Business and a respected Faculty of Law." },
      { name: "University of Alberta", strength: "Engineering / Medical", notes: "Strong in energy sciences, natural sciences, and medicine." },
      { name: "Université de Montréal", strength: "Medical / Engineering", notes: "Leading French-language university with strong medical and AI research." },
      { name: "University of Ottawa", strength: "Law / Engineering", notes: "Bilingual hub known for civil law and common law programs." },
    ],
    moderate: [
      { name: "Dalhousie University", strength: "Medical / Law", notes: "Affordable East Coast option, respected for health sciences and law." },
      { name: "University of Manitoba", strength: "Engineering / Medical", notes: "Budget-friendly research university with solid engineering and medicine." },
      { name: "University of Saskatchewan", strength: "Medical / Engineering", notes: "Lower tuition with strong agriculture, medicine, and engineering programs." },
      { name: "Carleton University", strength: "Engineering / Management", notes: "Affordable Ottawa-based school with growing tech and business programs." },
      { name: "University of Calgary", strength: "Engineering / Law", notes: "Reasonably priced with strong energy engineering and law faculties." },
      { name: "Simon Fraser University", strength: "Management / Engineering", notes: "Cost-effective BC option with a respected Beedie School of Business." },
      { name: "York University", strength: "Management / Law", notes: "Schulich School of Business is well regarded; moderate tuition for Ontario." },
      { name: "University of Windsor", strength: "Engineering / Law", notes: "Budget-friendly with strong engineering and a well-known law school." },
      { name: "Memorial University of Newfoundland", strength: "Medical / Engineering", notes: "Among Canada's most affordable tuition rates, decent medical and engineering programs." },
      { name: "Laurentian University", strength: "Management / Engineering", notes: "Small, affordable institution with practical business and mining engineering programs." },
    ],
  },
  {
    name: "Australia",
    slug: "australia",
    flag: "🇦🇺",
    top: [
      { name: "University of Melbourne", strength: "Medical / Law / Management", notes: "Australia's top-ranked university; renowned Melbourne Law School and Medical School." },
      { name: "University of Sydney", strength: "Medical / Engineering / Law", notes: "One of Australia's oldest and most prestigious, strong across all major fields." },
      { name: "Australian National University (ANU)", strength: "Law / Management", notes: "Top choice for law, public policy, and international relations." },
      { name: "University of New South Wales (UNSW)", strength: "Engineering / Business", notes: "Leading engineering school and the well-regarded UNSW Business School." },
      { name: "University of Queensland", strength: "Medical / Engineering", notes: "Strong biomedical research and engineering programs." },
      { name: "Monash University", strength: "Medical / Engineering / Management", notes: "Australia's largest university; strong pharmacy, medicine, and business school." },
      { name: "University of Western Australia", strength: "Engineering / Medical", notes: "Strong in mining engineering and medical research." },
      { name: "University of Adelaide", strength: "Engineering / Medical", notes: "Historic university known for engineering and health sciences." },
      { name: "Macquarie University", strength: "Management / Law", notes: "Highly regarded for business, accounting, and law programs." },
      { name: "RMIT University", strength: "Engineering / Management", notes: "Strong industry links in engineering, design, and business." },
    ],
    moderate: [
      { name: "Curtin University", strength: "Engineering / Management", notes: "Affordable Perth-based university with solid engineering and business programs." },
      { name: "Deakin University", strength: "Management / Engineering", notes: "Budget-friendly with flexible study options and a respected business faculty." },
      { name: "Griffith University", strength: "Law / Medical", notes: "Reasonably priced with a strong criminology/law and health sciences focus." },
      { name: "University of Newcastle", strength: "Medical / Engineering", notes: "Known for its innovative, affordable medical program (PBL model)." },
      { name: "University of South Australia", strength: "Engineering / Management", notes: "Cost-effective with strong industry-oriented engineering and business degrees." },
      { name: "Flinders University", strength: "Medical / Law", notes: "Moderate fees with a well-regarded medical school in Adelaide." },
      { name: "James Cook University", strength: "Medical / Engineering", notes: "Affordable tropical-health and engineering specializations." },
      { name: "Victoria University", strength: "Management", notes: "Budget-friendly Melbourne option focused on business and vocational pathways." },
      { name: "University of Tasmania", strength: "Medical / Law", notes: "Lower cost of living and tuition; solid medicine and law faculties." },
      { name: "Western Sydney University", strength: "Engineering / Management", notes: "Affordable, practical degrees with strong industry placement support." },
    ],
  },
  {
    name: "UK",
    slug: "uk",
    flag: "🇬🇧",
    top: [
      { name: "University of Oxford", strength: "Law / Medical / Management", notes: "World-renowned across law, medicine, and the Saïd Business School." },
      { name: "University of Cambridge", strength: "Engineering / Medical / Law", notes: "Top-tier engineering, medicine, and law programs globally." },
      { name: "Imperial College London", strength: "Engineering / Medical", notes: "Specialist STEM institution; outstanding engineering and medicine." },
      { name: "London School of Economics (LSE)", strength: "Management / Law", notes: "World leader in economics, management, and law." },
      { name: "UCL (University College London)", strength: "Medical / Engineering / Law", notes: "Broad strength across medicine, engineering, and law faculties." },
      { name: "University of Edinburgh", strength: "Medical / Law / Management", notes: "Historic Scottish university, strong medicine and law schools." },
      { name: "King's College London", strength: "Medical / Law", notes: "Renowned medical school and dentistry; strong law faculty." },
      { name: "University of Manchester", strength: "Engineering / Management", notes: "Major engineering research output and Alliance Manchester Business School." },
      { name: "University of Warwick", strength: "Management / Engineering", notes: "Warwick Business School is among the UK's best for management." },
      { name: "University of Bristol", strength: "Engineering / Medical / Law", notes: "Strong aerospace engineering, medicine, and law programs." },
    ],
    moderate: [
      { name: "University of Leeds", strength: "Engineering / Law / Management", notes: "Affordable, well-rounded with solid engineering and law schools." },
      { name: "University of Sheffield", strength: "Engineering / Medical", notes: "Known for materials engineering at moderate tuition costs." },
      { name: "University of Nottingham", strength: "Law / Management / Medical", notes: "Good value with a respected law school and medical school." },
      { name: "Newcastle University", strength: "Medical / Engineering", notes: "Affordable with strong dental and medical programs." },
      { name: "University of Liverpool", strength: "Medical / Engineering", notes: "Lower-cost option with a historic medical school." },
      { name: "Cardiff University", strength: "Law / Medical", notes: "Budget-friendly Welsh university with a strong law school." },
      { name: "Queen's University Belfast", strength: "Engineering / Law / Medical", notes: "Among the most affordable Russell Group universities." },
      { name: "University of Aberdeen", strength: "Engineering / Law / Medical", notes: "Known for petroleum engineering at relatively lower fees." },
      { name: "Coventry University", strength: "Engineering / Management", notes: "Practical, industry-linked degrees at affordable tuition rates." },
      { name: "University of Hertfordshire", strength: "Engineering / Management", notes: "Budget-friendly with strong employability-focused programs." },
    ],
  },
  {
    name: "Germany",
    slug: "germany",
    flag: "🇩🇪",
    top: [
      { name: "Technical University of Munich (TUM)", strength: "Engineering", notes: "Germany's top engineering and technology university." },
      { name: "Ludwig Maximilian University of Munich (LMU)", strength: "Medical / Law", notes: "Top-ranked for medicine and law in Germany." },
      { name: "Heidelberg University", strength: "Medical", notes: "Germany's oldest university; outstanding medical research." },
      { name: "RWTH Aachen University", strength: "Engineering", notes: "Premier technical university, especially for mechanical engineering." },
      { name: "Humboldt University of Berlin", strength: "Law / Management", notes: "Historic and prestigious, strong law and social sciences faculty." },
      { name: "Free University of Berlin (FU Berlin)", strength: "Medical / Law", notes: "Strong life sciences and law programs in the capital." },
      { name: "University of Freiburg", strength: "Medical / Engineering", notes: "Well-regarded medical school and engineering faculty." },
      { name: "Karlsruhe Institute of Technology (KIT)", strength: "Engineering", notes: "Top technical institute, especially for computer science/engineering." },
      { name: "University of Mannheim", strength: "Management / Law", notes: "Germany's top-ranked business school; strong law faculty." },
      { name: "Goethe University Frankfurt", strength: "Management / Law", notes: "Located in Germany's financial hub; strong finance and law programs." },
    ],
    moderate: [
      { name: "University of Stuttgart", strength: "Engineering", notes: "Affordable (low/no tuition) with strong automotive engineering ties." },
      { name: "TU Berlin", strength: "Engineering / Management", notes: "Low tuition fees with solid engineering and management programs." },
      { name: "University of Hamburg", strength: "Law / Management", notes: "Affordable tuition with a respected law school." },
      { name: "University of Cologne", strength: "Law / Management", notes: "One of Germany's largest, with low fees and a strong law faculty." },
      { name: "TU Dresden", strength: "Engineering / Medical", notes: "Budget-friendly with strong engineering and medical research." },
      { name: "University of Bonn", strength: "Medical / Law", notes: "Low-cost public university with respected medicine and law." },
      { name: "Leipzig University", strength: "Medical / Management", notes: "Affordable with a growing reputation in medicine and management." },
      { name: "Ruhr University Bochum", strength: "Engineering / Law", notes: "Cost-effective with solid engineering and law programs." },
      { name: "University of Duisburg-Essen", strength: "Engineering / Medical", notes: "Affordable tuition with practical engineering and medical tracks." },
      { name: "University of Bremen", strength: "Engineering", notes: "Low tuition costs with strong marine and space engineering focus." },
    ],
  },
  {
    name: "USA",
    slug: "usa",
    flag: "🇺🇸",
    top: [
      { name: "Harvard University", strength: "Law / Medical / Management", notes: "World-leading law school, medical school, and Harvard Business School." },
      { name: "Massachusetts Institute of Technology (MIT)", strength: "Engineering", notes: "Global leader in engineering and applied sciences." },
      { name: "Stanford University", strength: "Engineering / Management / Law", notes: "Top-ranked engineering, law, and Graduate School of Business." },
      { name: "Johns Hopkins University", strength: "Medical", notes: "Consistently ranked the #1 medical school in the US." },
      { name: "Yale University", strength: "Law / Medical", notes: "Yale Law School is among the most prestigious in the world." },
      { name: "University of Pennsylvania", strength: "Management / Medical / Law", notes: "Home to Wharton School, a top-ranked business school." },
      { name: "Columbia University", strength: "Law / Medical / Management", notes: "Strong law, medical, and business programs in New York City." },
      { name: "University of California, Berkeley", strength: "Engineering / Management", notes: "Top public university; outstanding engineering and Haas Business School." },
      { name: "California Institute of Technology (Caltech)", strength: "Engineering", notes: "Elite, research-intensive engineering and science institution." },
      { name: "University of Chicago", strength: "Law / Management", notes: "Top-ranked law school and Booth School of Business." },
    ],
    moderate: [
      { name: "Penn State University", strength: "Engineering / Management", notes: "Large public university with affordable in-state tuition and solid engineering." },
      { name: "University of Texas at Austin", strength: "Engineering / Management / Law", notes: "Lower cost for residents; strong engineering and McCombs business school." },
      { name: "University of Florida", strength: "Engineering / Medical / Law", notes: "Affordable public option with strong engineering and medical programs." },
      { name: "Arizona State University", strength: "Engineering / Management", notes: "Known for accessibility and strong online/affordable degree options." },
      { name: "University of Illinois Urbana-Champaign", strength: "Engineering", notes: "Strong, moderately priced engineering programs for state residents." },
      { name: "Indiana University Bloomington", strength: "Management / Law", notes: "Affordable with the well-regarded Kelley School of Business." },
      { name: "University of Iowa", strength: "Medical / Law", notes: "Lower-cost public university with a respected medical and law school." },
      { name: "University of Pittsburgh", strength: "Medical / Engineering", notes: "Strong medical research at moderate public-university tuition." },
      { name: "Rutgers University", strength: "Engineering / Management / Law", notes: "Affordable New Jersey public university with broad program strength." },
      { name: "University of Cincinnati", strength: "Engineering / Medical", notes: "Budget-friendly with co-op engineering programs and a solid medical school." },
    ],
  },
  {
    name: "UAE",
    slug: "uae",
    flag: "🇦🇪",
    top: [
      { name: "Khalifa University", strength: "Engineering", notes: "UAE's top STEM/research university; strong ties to ADNOC and Mubadala." },
      { name: "United Arab Emirates University (UAEU)", strength: "Medical / Engineering / Law", notes: "Oldest federal university; offers medicine, engineering, and law." },
      { name: "American University of Sharjah (AUS)", strength: "Management / Engineering", notes: "Leading for business and employer reputation in the UAE." },
      { name: "University of Sharjah", strength: "Medical / Law", notes: "Ranked #1 in the UAE for law in THE Subject Rankings; strong medicine and dentistry." },
      { name: "American University in Dubai (AUD)", strength: "Management", notes: "American-model business education, well recognized in the Gulf." },
      { name: "Abu Dhabi University", strength: "Law / Management / Engineering", notes: "Ranked best in the UAE for law; strong business and engineering." },
      { name: "Zayed University", strength: "Management", notes: "Federal institution focused on business, media, and innovation." },
      { name: "NYU Abu Dhabi", strength: "Management / Engineering", notes: "Selective branch campus offering a globally recognized NYU degree." },
      { name: "University of Birmingham Dubai", strength: "Engineering / Management", notes: "Only Russell Group branch campus in the UAE." },
      { name: "Heriot-Watt University Dubai", strength: "Engineering / Management", notes: "Particularly strong for engineering and actuarial science." },
    ],
    moderate: [
      { name: "Ajman University", strength: "Engineering / Management", notes: "Affordable, well-regarded for education and engineering programs." },
      { name: "BITS Pilani Dubai", strength: "Engineering", notes: "Same BITS Pilani degree and curriculum at competitive Gulf tuition." },
      { name: "Amity University Dubai", strength: "Engineering / Management / Law", notes: "One of the more affordable options for Indian-curriculum students." },
      { name: "Manipal Academy of Higher Education (MAHE) Dubai", strength: "Engineering / Management", notes: "Reputable Indian-origin university at moderate UAE tuition rates." },
      { name: "University of Wollongong in Dubai", strength: "Management / Engineering", notes: "Top-ranked Australian branch campus in the region." },
      { name: "Curtin University Dubai", strength: "Engineering / Management", notes: "Globally ranked Australian university with moderate fees." },
      { name: "Middlesex University Dubai", strength: "Management / Law", notes: "Affordable UK branch campus with broad program offerings." },
      { name: "Canadian University Dubai", strength: "Engineering / Management", notes: "Canadian-style curriculum, ranked #1 in Dubai for several years." },
      { name: "American University in the Emirates", strength: "Management / Engineering", notes: "Budget-friendly business and engineering programs." },
      { name: "Skyline University College", strength: "Management", notes: "Cost-effective business-focused private university in Sharjah." },
    ],
  },
  {
    name: "Uzbekistan",
    slug: "uzbekistan",
    flag: "🇺🇿",
    top: [
      { name: "National University of Uzbekistan", strength: "Management / Law", notes: "Country's leading research university; strong sciences and humanities." },
      { name: "Tashkent State Technical University", strength: "Engineering", notes: "Oldest and most respected engineering institute in Uzbekistan." },
      { name: "Tashkent Medical Academy", strength: "Medical", notes: "Oldest (1919) and most prestigious medical institution in the country." },
      { name: "Tashkent State University of Law", strength: "Law", notes: "Leading institution for legal education in Uzbekistan." },
      { name: "Westminster International University in Tashkent", strength: "Management", notes: "UK-standard business, economics, and management degrees." },
      { name: "University of World Economy and Diplomacy", strength: "Management / Law", notes: "Specializes in diplomacy, international law, and economics." },
      { name: "Samarkand State Medical University", strength: "Medical", notes: "Highly regarded medical institute with strong clinical training." },
      { name: "Tashkent State Dental Institute", strength: "Medical", notes: "Specializes in dental medicine at moderate tuition." },
      { name: "Tashkent University of Information Technologies", strength: "Engineering", notes: "Leading institution for IT and computer engineering." },
      { name: "Tashkent Institute of Finance", strength: "Management", notes: "Specialist institute for finance and economic management." },
    ],
    moderate: [
      { name: "Andijan State Medical Institute", strength: "Medical", notes: "Affordable medical program with strong clinical exposure (est. 1955)." },
      { name: "Bukhara State Medical Institute", strength: "Medical", notes: "Budget-friendly with international collaborations for medicine." },
      { name: "Fergana Medical Institute of Public Health", strength: "Medical", notes: "Affordable medical degree with a good academic environment." },
      { name: "Termez State Medical Institute", strength: "Medical", notes: "Newer, English-taught medical institute with welcoming international intake." },
      { name: "Tashkent Pediatric Medical Institute", strength: "Medical", notes: "Specializes in pediatric medicine at moderate tuition." },
      { name: "Tashkent State Dental Institute", strength: "Medical", notes: "Best choice in the country specifically for dental medicine." },
      { name: "Samarkand State University", strength: "Management / Law", notes: "Historic, affordable university strong in humanities and sciences." },
      { name: "Tashkent State Agrarian University", strength: "Engineering", notes: "Budget-friendly, specializes in agricultural engineering." },
      { name: "Tashkent Automobile and Road Construction Institute", strength: "Engineering", notes: "Top-ranked in the country specifically for civil/automotive engineering." },
      { name: "Karshi Engineering and Economics Institute", strength: "Engineering / Management", notes: "Budget-friendly regional option for engineering and economics." },
    ],
  },
  {
    name: "Kyrgyzstan",
    slug: "kyrgyzstan",
    flag: "🇰🇬",
    top: [
      { name: "Kyrgyz State Technical University", strength: "Engineering", notes: "The flagship engineering institution in Kyrgyzstan." },
      { name: "Kyrgyz National University", strength: "Management / Law", notes: "Largest and most comprehensive national university." },
      { name: "American University of Central Asia (AUCA)", strength: "Management / Law", notes: "Liberal-arts style education with strong international recognition." },
      { name: "Kyrgyz-Russian Slavic University (KRSU)", strength: "Medical / Engineering", notes: "Highly regarded for medicine taught in Russian/English." },
      { name: "Kyrgyzstan-Turkey Manas University", strength: "Management / Engineering", notes: "Strong international partnerships, ranked for business studies." },
      { name: "International Higher School of Medicine (IHSM)", strength: "Medical", notes: "One of the top NMC-recognized medical universities for international students." },
      { name: "Kyrgyz State Medical Academy", strength: "Medical", notes: "National medical academy with strong clinical training base." },
      { name: "Osh State University", strength: "Medical / Engineering", notes: "Major regional university, strong in medicine and engineering." },
      { name: "Kyrgyz Economic University", strength: "Management", notes: "Country's dedicated institution for economics and trade." },
      { name: "International University of Kyrgyzstan", strength: "Medical / Engineering / Management", notes: "Diverse programs with an international student orientation." },
    ],
    moderate: [
      { name: "Jalal-Abad State University", strength: "Medical", notes: "Affordable regional university with open winter/fall medical intakes." },
      { name: "Bishkek International Medical Institute (BIMI)", strength: "Medical", notes: "Budget-friendly medical institute popular with international students." },
      { name: "Osh State Medical University", strength: "Medical", notes: "Lower-cost medical program with steady international enrollment." },
      { name: "Jalalabad State Medical Institute", strength: "Medical", notes: "Affordable medical institute in the Fergana Valley region." },
      { name: "Salymbekov University", strength: "Medical", notes: "Private, moderately priced medical and health sciences institute." },
      { name: "Asian Medical Institute", strength: "Medical", notes: "Budget-friendly with NMC/WHO-recognized medical programs." },
      { name: "Kyrgyz State University of Construction, Transport and Architecture", strength: "Engineering", notes: "Affordable specialist institute for civil engineering." },
      { name: "Naryn State University", strength: "Management / Engineering", notes: "Small, low-cost regional university with general programs." },
      { name: "International School of Medicine, Bishkek", strength: "Medical", notes: "Affordable option with English-medium instruction." },
      { name: "Talas State University", strength: "Management", notes: "Budget regional institution offering general management programs." },
    ],
  },
  {
    name: "Georgia",
    slug: "georgia",
    flag: "🇬🇪",
    top: [
      { name: "Ivane Javakhishvili Tbilisi State University (TSU)", strength: "Law / Medical / Management", notes: "Georgia's oldest and most prestigious university; #1 in QS rankings nationally." },
      { name: "Tbilisi State Medical University (TSMU)", strength: "Medical", notes: "Main center of medical education in Georgia, nearly a century old." },
      { name: "Georgian Technical University (GTU)", strength: "Engineering", notes: "Leading technical university with over 250 programs, strong international ties." },
      { name: "Caucasus University", strength: "Law / Management", notes: "Modern campus known for business, law, and international relations." },
      { name: "University of Georgia", strength: "Law / Engineering", notes: "Top-ranked locally for law and biotechnology." },
      { name: "Ilia State University", strength: "Management / Law", notes: "Globally recognized in QS rankings; strong social sciences and law." },
      { name: "David Tvildiani Medical University", strength: "Medical", notes: "Internationally accredited, popular with international medical students." },
      { name: "Georgian American University", strength: "Management / Law / Medical", notes: "Offers business, law, diplomacy, and medicine programs." },
      { name: "Batumi Shota Rustaveli State University", strength: "Medical", notes: "Top public university in coastal Batumi, specializing in medicine and nursing." },
      { name: "Georgian National University SEU", strength: "Medical / Management / Law", notes: "Largest private university, strong across medicine, law, and business." },
    ],
    moderate: [
      { name: "East European University", strength: "Medical / Management", notes: "Affordable English-language medical and business programs." },
      { name: "New Vision University", strength: "Medical", notes: "NMC/WHO-accredited medical program at moderate tuition." },
      { name: "Alte University", strength: "Medical / Management", notes: "Budget-friendly option popular for MBBS among international students." },
      { name: "Petre Shotadze Tbilisi Medical Academy", strength: "Medical", notes: "Lower-cost medical academy with practical clinical training." },
      { name: "Tbilisi Medical University 'Hippocrates'", strength: "Medical", notes: "Affordable, internationally oriented medical university." },
      { name: "Caucasus International University (CIU)", strength: "Medical / Management / Law", notes: "Moderate fees across medicine, business, and law programs." },
      { name: "Geomedi State University", strength: "Medical", notes: "Cost-effective medical degree with international accreditation." },
      { name: "Akaki Tsereteli State University", strength: "Engineering / Medical", notes: "Affordable regional university in Kutaisi." },
      { name: "Sokhumi State University", strength: "Management / Law", notes: "Low-cost option carrying on Georgian academic traditions." },
      { name: "Webster University Tbilisi", strength: "Management", notes: "Globally recognized American business curriculum at moderate cost." },
    ],
  },
  {
    name: "Russia",
    slug: "russia",
    flag: "🇷🇺",
    top: [
      { name: "Lomonosov Moscow State University (MSU)", strength: "Medical / Engineering / Law", notes: "Russia's top-ranked university across nearly all disciplines." },
      { name: "I.M. Sechenov First Moscow State Medical University", strength: "Medical", notes: "Russia's #1 medical university, founded 1758; strong global reputation." },
      { name: "MGIMO University", strength: "Law / Management", notes: "Premier institution for international relations, law, and diplomacy." },
      { name: "Moscow Institute of Physics and Technology (MIPT)", strength: "Engineering", notes: "Top technical/engineering research university." },
      { name: "Saint Petersburg State University", strength: "Law / Medical / Management", notes: "One of Russia's oldest and most respected universities." },
      { name: "Bauman Moscow State Technical University", strength: "Engineering", notes: "Russia's leading engineering school, especially aerospace and robotics." },
      { name: "Higher School of Economics (HSE)", strength: "Management / Law", notes: "Top-ranked for economics, management, and social sciences." },
      { name: "Peoples' Friendship University of Russia (RUDN)", strength: "Medical / Engineering", notes: "Strong international student base; respected medical programs." },
      { name: "Kazan Federal University", strength: "Medical / Engineering", notes: "Major regional research university, strong medicine and engineering." },
      { name: "Pirogov Russian National Research Medical University", strength: "Medical", notes: "Strong research focus and clinical training." },
    ],
    moderate: [
      { name: "Volgograd State Medical University", strength: "Medical", notes: "Affordable medical program popular with international students." },
      { name: "Tver State Medical University", strength: "Medical", notes: "Budget-friendly medical degree with NMC/WHO recognition." },
      { name: "Ryazan State Medical University", strength: "Medical", notes: "Lower-cost medical institute with solid clinical training." },
      { name: "Orenburg State Medical University", strength: "Medical", notes: "Affordable regional medical university with global student intake." },
      { name: "Altai State Medical University", strength: "Medical", notes: "Budget option with practical, hands-on clinical exposure." },
      { name: "Bashkir State Medical University", strength: "Medical", notes: "Moderate fees with a long-established medical curriculum." },
      { name: "Voronezh State Technical University", strength: "Engineering", notes: "Affordable engineering programs with regional industry ties." },
      { name: "Ural Federal University", strength: "Engineering / Management", notes: "Cost-effective with strong engineering and metallurgy programs." },
      { name: "Tomsk Polytechnic University", strength: "Engineering", notes: "Affordable, well-regarded technical university in Siberia." },
      { name: "Novosibirsk State University", strength: "Engineering / Management", notes: "Strong sciences focus at moderate tuition levels." },
    ],
  },
  {
    name: "India",
    slug: "india",
    flag: "🇮🇳",
    top: [
      { name: "Indian Institute of Technology Bombay (IIT Bombay)", strength: "Engineering", notes: "Among India's top-ranked engineering institutions." },
      { name: "Indian Institute of Technology Delhi (IIT Delhi)", strength: "Engineering", notes: "Premier engineering and technology institute." },
      { name: "All India Institute of Medical Sciences (AIIMS), Delhi", strength: "Medical", notes: "India's top-ranked medical institution." },
      { name: "Indian Institute of Management Ahmedabad (IIM-A)", strength: "Management", notes: "India's leading business school for the MBA/PGP." },
      { name: "National Law School of India University (NLSIU), Bangalore", strength: "Law", notes: "India's top-ranked law school." },
      { name: "Indian Institute of Science (IISc), Bangalore", strength: "Engineering / Science", notes: "India's top research institute for science and engineering." },
      { name: "Indian Institute of Technology Madras (IIT Madras)", strength: "Engineering", notes: "Consistently ranked #1 engineering institute in India (NIRF)." },
      { name: "Christian Medical College (CMC), Vellore", strength: "Medical", notes: "Among India's most respected medical colleges, strong clinical training." },
      { name: "Indian Institute of Management Bangalore (IIM-B)", strength: "Management", notes: "Top-tier management school with strong industry connections." },
      { name: "National Law University (NLU), Delhi", strength: "Law", notes: "Highly ranked law school known for its rigorous curriculum." },
    ],
    moderate: [
      { name: "Jamia Millia Islamia", strength: "Engineering / Law / Management", notes: "Affordable central university with respected programs across fields." },
      { name: "Banaras Hindu University (BHU)", strength: "Medical / Engineering", notes: "Low public-university fees with a strong medical and engineering faculty." },
      { name: "Aligarh Muslim University (AMU)", strength: "Medical / Engineering / Law", notes: "Affordable, century-old university with broad program strength." },
      { name: "Symbiosis Law School, Pune", strength: "Law", notes: "Reputable private law school at moderate tuition compared to NLUs." },
      { name: "Government Medical College, Nagpur", strength: "Medical", notes: "Low-cost government medical college with solid clinical exposure." },
      { name: "Vellore Institute of Technology (VIT)", strength: "Engineering", notes: "Well-regarded private engineering university at moderate fees." },
      { name: "Symbiosis Institute of Business Management (SIBM), Pune", strength: "Management", notes: "Strong placement record at more accessible fees than top IIMs." },
      { name: "Manipal Academy of Higher Education", strength: "Medical / Engineering", notes: "Reputed private university with broad program offerings." },
      { name: "Gujarat National Law University (GNLU)", strength: "Law", notes: "Well-ranked national law university with moderate fee structure." },
      { name: "SRM Institute of Science and Technology", strength: "Engineering / Management", notes: "Large private university known for affordable engineering and management." },
    ],
  },
];

export const getCountryBySlug = (slug: string | undefined) =>
  countryCollegeData.find((country) => country.slug === slug?.toLowerCase());
